### ISSUE TITLE
Ruby failure on bot-sync-github

### ISSUE THREAD

**Issue by adib** [modcloth-labs/github-xcode-bot-builder#11]
Apparently Ruby crashes when running `bot-sync-github`

```
$ ./bot-sync-github 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- parseconfig (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/i011842/Applications/github-xcode-bot-builder-0.0.2/lib/bot_config.rb:2:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/i011842/Applications/github-xcode-bot-builder-0.0.2/lib/bot_builder.rb:7:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/i011842/Applications/github-xcode-bot-builder-0.0.2/lib/bot_cli.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from ./bot-sync-github:7:in `<main>'
```

On OS X 10.10.2 (14C1510) with Server version 4.0.3 (14S350)

**Comment by adib** [comment]
Probably related on Xcode 6 support issue in #10
